[package]
name = "moesi"
version = "0.1.0"
authors = ["Gui Andrade <gh@archshift.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
regex = "1.1"
lazy_static = "1.3.0"
wasm-bindgen = "0.2"
